TestSpace Project Creation

diff --git a/.github/workflows/init_repo.yml b/.github/workflows/init_repo.yml
--- a/.github/workflows/init_repo.yml
+++ b/.github/workflows/init_repo.yml
@@ -56,3 +56,29 @@ jobs:
           gh repo deploy-key add key.pub --repo ${{ vars.ci_report_repo_path }} --allow-write --title "Publication pour ${{ github.repository }}"
         env:
           GH_TOKEN: ${{ secrets.PAT_DYNAMIC_TEMPLATE }}
+
+      - name: "TestSpace Project Creation"
+        run: |
+          http_response=$(curl -o response.txt -w "%{response_code}" --no-progress-meter -X GET -H "Authorization: Token ${{ secrets.TESTSPACE_TOKEN }}" "https://${{ github.repository_owner }}.testspace.com/api/projects")
+          if [ $http_response != "200" ]; then
+            echo -e "${cRED}FATAL: Error when trying to get project list from testspace (${http_response}).${cSTOP}"
+            cat response.txt
+            exit 1
+          fi
+          found=$(jq ".[] | select(.source_repo_url==\"https://github.com/${{ github.repository }}\")" response.txt)
+          if [[ -z "$found" ]]; then
+            echo -e "${cGREEN}TestSpace Project is going to be created.${cSTOP}"
+            ret=$(curl --no-progress-meter -X POST \
+              -H "Authorization: Token ${{ secrets.TESTSPACE_TOKEN }}" \
+              -H "Content-Type: application/json" \
+              --data '{"name":"${${{ github.repository }}///:}", "source_repo": "'"github:${{ github.repository }}"'", "is_private": false}' \
+              "https://${{ github.repository_owner }}.testspace.com/api/projects")
+            echo $ret
+            testspace_project_id=$(jq '.id' <<< $ret)
+            testspace_project_name=$(jq '.name' <<< $found)
+            echo -e "${cGREEN}The TestSpace Project $testspace_project_name was created with id $testspace_project_id.${cSTOP}"
+          else
+            testspace_project_id=$(jq '.id' <<< $found)
+            testspace_project_name=$(jq '.name' <<< $found)
+            echo -e "${cBLUE}The TestSpace Project $testspace_project_name already exits with id $testspace_project_id.${cSTOP}"
+          fi
